weights: yolov5s.pt
cfg: /home/grzegorz/Documents/Politechnika/Semestr_5/WDSI/projekt_V2/yolov5/models/yolov5s.yaml
data: /home/grzegorz/Documents/Politechnika/Semestr_5/WDSI/projekt_V2/yolov5/data/road_sign_data.yaml
hyp: /home/grzegorz/Documents/Politechnika/Semestr_5/WDSI/projekt_V2/yolov5/data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 24
imgsz: 440
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 24
project: runs/train
name: yolo_road_det
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolo_road_det25
